#if UNITY_EDITOR
using Sirenix.OdinInspector;
using Sirenix.OdinInspector.Editor;
using System.Text;
using UnityEditor;
using UnityEngine;
using System.IO;

namespace Core
{
    internal class ClassForUnityTagsCreator : OdinEditorWindow
    {
        [ShowInInspector, FolderPath(AbsolutePath = true)] private string savePath = @"C:/Users/callu/Documents/GitHub/Lawnmower/Assets/Scripts/Core";
        [ShowInInspector] private string @namespace = "Core";

        private const string MenuPath = "Callum/Create Enum For Unity Tags";

        private const string ClassName = "UnityTags";

        [MenuItem(MenuPath)]
        private static void Init()
        {
            var window = CreateWindow<ClassForUnityTagsCreator>();
        }

        [Button]
        private void Create()
        {
            StringBuilder sb = new StringBuilder();

            sb.Append($"// Code generated by {nameof(ClassForUnityTagsCreator)}.cs. Use menu item \"{MenuPath}\" to update\n\n");

            if (@namespace != null)
            {
                sb.Append("namespace " + @namespace + "\n{\n");
            }

            sb.Append("public static class " + ClassName + "\n{\n");

            for (int i = 0; i < UnityEditorInternal.InternalEditorUtility.tags.Length; i++)
            {
                string name = UnityEditorInternal.InternalEditorUtility.tags[i];
                string varName = name.Replace(" ", "");

                sb.Append($"public const string {varName} = \"{name}\";\n");
            }

            sb.Append("}\n");

            if (@namespace != null)
            {
                sb.Append("}");
            }

            string filePath = savePath + "/" + ClassName + ".cs";

            if (File.Exists(filePath))
            {
                File.Delete(filePath);
            }

            using (FileStream stream = File.Create(filePath))
            {
                byte[] bytes = Encoding.UTF8.GetBytes(sb.ToString());
                stream.Write(bytes, 0, bytes.Length);
            }

            AssetDatabase.Refresh();

            Close();
        }
    }
}
#endif
