// Code generated by EnumForUnityLayersCreator.cs. Use menu item "Callum/Create Enum For Unity Layers" to update

namespace Core
{
public enum UnityLayers
{
Default = 0,
TransparentFX = 1,
Ignore_Raycast = 2,
Water = 4,
UI = 5,
PostProcessing = 8,
UiTile = 9,
}
}