// Code generated by EnumForScenesCreatorWindow.cs. Use menu item "Callum/EnumForScenesCreatorWindow" to update

namespace Core
{
    public enum UnityScene
    {
        None = -1,
        MainMenu = 0,
        LevelSelect = 1,
        Game = 2,
    }
}
